version: '3.8'

volumes:
  wordpress:
  mysql:

networks:
  wordpress_net:
    name: wordpress_net
    driver: bridge

services:
  wordpress:
    image: wordpress:6.0.2
    container_name: wordpress
    networks:
    - wordpress_net
    ports:
      - 8080:80
    depends_on:
      - mysqldb
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_USER: mysqluser
      WORDPRESS_DB_PASSWORD: mysqlpwd
      WORDPRESS_DB_NAME: wp-database

  mysqldb:
    image: mysql:8.0.30
    container_name: mysqldb
    networks:
      - wordpress_net
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: wp-database
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpwd